export type bool = boolean;
export type int8 = number;
export type int16 = number;
export type int32 = number;
export type int64 = bigint;
export type uint8 = number;
export type uint16 = number;
export type uint32 = number;
export type uint64 = bigint;
export type gostring = GoString;
export type float32 = number;
export type float64 = number;
export type int = bigint;
export type uint = bigint;
export type uintptr = bigint;
import type { GoString } from "@gotots/runtime/string-value.js";
