// Metric battery: the machine-gate measurement set required by the
// enforcement directive — per-body expansion distribution (median, p90,
// p95, p99, max), the top-20 largest and widest bodies, definition
// duplication, category byte conservation, and the unconditional
// egregious stop-the-line verdicts. Every fact joins through the dump's
// typed ledgers and exact corpus byte spans; source and output are
// compared in the SAME byte domain (ADR-0011).
//
//	GOTOTS_CORPUS_DIR=<pinned tsgo> GOTOTS_DUMP_DIR=<dump> gotots-metrics
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tsoniclang/gotots/internal/census"
	"github.com/tsoniclang/gotots/internal/shapegate"
	"github.com/tsoniclang/gotots/internal/translate"
)

type bodyExpansion struct {
	ID              string  `json:"id"`
	GoBytes         int     `json:"goBytes"`
	GeneratedBytes  int     `json:"generatedBytes"`
	Ratio           float64 `json:"ratio"`
	Implementations int     `json:"implementations"`
}

type report struct {
	SchemaVersion int `json:"schemaVersion"`
	// Denominators name every population per ADR-0011.
	BodiesJoined     int             `json:"bodiesJoined"`
	BodiesUnjoined   []string        `json:"bodiesUnjoined,omitempty"`
	TotalGoBytes     int             `json:"totalGoBytes"`
	TotalGenBytes    int             `json:"totalGeneratedBodyBytes"`
	Median           float64         `json:"expansionMedian"`
	P90              float64         `json:"expansionP90"`
	P95              float64         `json:"expansionP95"`
	P99              float64         `json:"expansionP99"`
	Max              float64         `json:"expansionMax"`
	Top20ByBytes     []bodyExpansion `json:"top20ByGeneratedBytes"`
	Top20ByRatio     []bodyExpansion `json:"top20ByRatio"`
	DuplicatedDefs   map[string]int  `json:"duplicatedSupportDefinitions,omitempty"`
	CategoryBytes    map[string]int  `json:"categoryBytes"`
	UnattributedByte int             `json:"unattributedBytes"`
	StopTheLine      []string        `json:"stopTheLine,omitempty"`
	// DimensionsPending names required battery dimensions this tool
	// does not yet measure — absence of a number is never silence.
	DimensionsPending []string `json:"dimensionsPending"`
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func readLedger(dumpDir, name string, out any) {
	data, err := os.ReadFile(filepath.Join(dumpDir, "ledgers", name))
	if err != nil {
		fail(err)
	}
	if err := json.Unmarshal(data, out); err != nil {
		fail(fmt.Errorf("%s: %w", name, err))
	}
}

func percentile(sorted []float64, p float64) float64 {
	if len(sorted) == 0 {
		return 0
	}
	index := int(p * float64(len(sorted)-1))
	return sorted[index]
}

func main() {
	corpusDir := os.Getenv("GOTOTS_CORPUS_DIR")
	dumpDir := os.Getenv("GOTOTS_DUMP_DIR")
	if corpusDir == "" || dumpDir == "" {
		fail(fmt.Errorf("set GOTOTS_CORPUS_DIR and GOTOTS_DUMP_DIR"))
	}

	var declarations []census.DeclarationRecord
	readLedger(dumpDir, "declarations.json", &declarations)
	var artifacts []translate.ImplementationArtifact
	readLedger(dumpDir, "implementation-artifacts.json", &artifacts)
	var externSymbols []struct {
		Module     string `json:"Module"`
		Symbol     string `json:"Symbol"`
		Obligation string `json:"Obligation"`
	}
	readLedger(dumpDir, "extern-symbols.json", &externSymbols)

	// Generated bytes per SOURCE body: the sum of its implementation
	// artifact files (exact bytes, ledger-joined).
	generatedBySource := map[string]int{}
	implementationsBySource := map[string]int{}
	for _, artifact := range artifacts {
		full := filepath.Join(dumpDir, filepath.FromSlash(artifact.ArtifactPath))
		info, err := os.Stat(full)
		if err != nil {
			fail(fmt.Errorf("ledger artifact missing: %w", err))
		}
		generatedBySource[artifact.SourceID] += int(info.Size())
		implementationsBySource[artifact.SourceID]++
	}

	out := &report{SchemaVersion: 1, CategoryBytes: map[string]int{},
		DimensionsPending: []string{"tokens", "ast-nodes", "call-width", "tsc-rss", "tsc-time", "runtime"}}
	var expansions []bodyExpansion
	for _, decl := range declarations {
		if decl.Scope != "production" || (decl.Kind != "func" && decl.Kind != "method") || !decl.HasBody {
			continue
		}
		generated, joined := generatedBySource[decl.ID]
		if !joined {
			out.BodiesUnjoined = append(out.BodiesUnjoined, decl.ID)
			continue
		}
		// Exact byte spans recorded by the census producer — never a
		// line approximation.
		goBytes := decl.EndByte - decl.StartByte
		if goBytes <= 0 {
			out.BodiesUnjoined = append(out.BodiesUnjoined, decl.ID+" (no byte span recorded)")
			continue
		}
		expansions = append(expansions, bodyExpansion{
			ID: decl.ID, GoBytes: goBytes, GeneratedBytes: generated,
			Ratio:           float64(generated) / float64(goBytes),
			Implementations: implementationsBySource[decl.ID],
		})
		out.TotalGoBytes += goBytes
		out.TotalGenBytes += generated
	}
	out.BodiesJoined = len(expansions)
	sort.Slice(expansions, func(i, j int) bool { return expansions[i].Ratio < expansions[j].Ratio })
	ratios := make([]float64, len(expansions))
	for i, e := range expansions {
		ratios[i] = e.Ratio
	}
	out.Median = percentile(ratios, 0.50)
	out.P90 = percentile(ratios, 0.90)
	out.P95 = percentile(ratios, 0.95)
	out.P99 = percentile(ratios, 0.99)
	out.Max = percentile(ratios, 1.0)
	byRatio := append([]bodyExpansion{}, expansions...)
	for i, j := 0, len(byRatio)-1; i < j; i, j = i+1, j-1 {
		byRatio[i], byRatio[j] = byRatio[j], byRatio[i]
	}
	if len(byRatio) > 20 {
		byRatio = byRatio[:20]
	}
	out.Top20ByRatio = byRatio
	byBytes := append([]bodyExpansion{}, expansions...)
	sort.Slice(byBytes, func(i, j int) bool { return byBytes[i].GeneratedBytes > byBytes[j].GeneratedBytes })
	if len(byBytes) > 20 {
		byBytes = byBytes[:20]
	}
	out.Top20ByBytes = byBytes

	// Definition duplication, class 1: cross-module support-definition
	// copies from the typed extern-symbol ledger.
	copies := map[string]int{}
	for _, record := range externSymbols {
		if record.Obligation == "" {
			copies[record.Symbol]++
		}
	}
	// Definition duplication, class 2: AST-authoritative cross-module
	// joins over every generated core module through the pinned
	// compiler (functions, classes, AND type aliases — the measured
	// 42.4% class). Env-selectable because parsing the largest modules
	// is itself a heavy step of this heavy tool.
	if os.Getenv("GOTOTS_METRICS_AST") != "" {
		node := os.Getenv("GOTOTS_NODE")
		if node == "" {
			node = "node"
		}
		tsDir := os.Getenv("GOTOTS_TSC_DIR")
		if tsDir == "" {
			tsDir = "product/node_modules/typescript"
		}
		coreModules, err := filepath.Glob(filepath.Join(dumpDir, "core", "*", "package.ts"))
		if err != nil {
			fail(err)
		}
		shapes, err := shapegate.ExtractShapes(node, tsDir, coreModules)
		if err != nil {
			fail(fmt.Errorf("AST duplication pass: %w", err))
		}
		for identity, files := range shapegate.DuplicateDefinitions(shapes) {
			copies[identity] = len(files)
		}
	}
	out.DuplicatedDefs = map[string]int{}
	for symbol, count := range copies {
		if count > 1 {
			out.DuplicatedDefs[symbol] = count
		}
	}

	// Category byte conservation over the dump tree: every byte in
	// exactly one category; the total must equal the walked total.
	total := 0
	err := filepath.WalkDir(dumpDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		relative, _ := filepath.Rel(dumpDir, path)
		relative = filepath.ToSlash(relative)
		category := "unattributed"
		switch {
		case strings.HasPrefix(relative, "core/"):
			category = "generated-core"
		case strings.HasPrefix(relative, "external-stubs/"):
			category = "generated-external-contracts"
		case strings.HasPrefix(relative, "language-abi/"):
			category = "generated-abi"
		case strings.HasPrefix(relative, "interfaces/"):
			category = "generated-interface-artifacts"
		case strings.HasPrefix(relative, "analysis/"):
			category = "analysis-artifacts"
		case strings.HasPrefix(relative, "ledgers/"):
			category = "ledgers"
		}
		out.CategoryBytes[category] += int(info.Size())
		total += int(info.Size())
		return nil
	})
	if err != nil {
		fail(err)
	}
	sum := 0
	for category, bytes := range out.CategoryBytes {
		if category == "unattributed" {
			out.UnattributedByte = bytes
			continue
		}
		sum += bytes
	}
	if sum+out.UnattributedByte != total {
		fail(fmt.Errorf("category conservation violated: %d + %d != %d", sum, out.UnattributedByte, total))
	}

	// Unconditional stop-the-line verdicts over the measured worst
	// cases and duplication counts.
	var fixtures []shapegate.FixtureMeasurement
	for _, e := range out.Top20ByRatio {
		fixtures = append(fixtures, shapegate.FixtureMeasurement{
			FixtureID: e.ID, Verdict: "exception", GoBytes: e.GoBytes, GeneratedBytes: e.GeneratedBytes,
		})
	}
	for _, failure := range shapegate.EgregiousReport(fixtures, copies) {
		out.StopTheLine = append(out.StopTheLine, failure.String())
	}

	sort.Strings(out.BodiesUnjoined)
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", " ")
	if err := encoder.Encode(out); err != nil {
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "bodies=%d median=%.2f p90=%.2f p95=%.2f p99=%.2f max=%.2f stop-the-line=%d dup-defs=%d unattributed=%d unjoined=%d\n",
		out.BodiesJoined, out.Median, out.P90, out.P95, out.P99, out.Max, len(out.StopTheLine), len(out.DuplicatedDefs), out.UnattributedByte, len(out.BodiesUnjoined))
	// The battery is a GATE: stop-the-line conditions, unattributed
	// bytes, or unjoined bodies exit nonzero — reporting without
	// failing is the exact anti-pattern the enforcement verdict bans.
	if len(out.StopTheLine) > 0 || out.UnattributedByte > 0 || len(out.BodiesUnjoined) > 0 {
		os.Exit(2)
	}
}
