// Package emit prints IR as deterministic, statically typed, erasable-
// syntax TypeScript: strict ESM with explicit .js relative imports,
// provenance headers, and fully parenthesized expressions so precedence is
// never ambiguous. Every integer operation lowers through the versioned
// language ABI unless the operation is exact under direct JS semantics.
package emit

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/tsoniclang/gotots/internal/ir"
)

// Provenance identifies the inputs of one generated file.
type Provenance struct {
	SchemaVersion  int    `json:"schemaVersion"`
	SourceRevision string `json:"sourceRevision"`
	ProfileHash    string `json:"profileHash"`
	AbiVersion     int    `json:"abiVersion"`
	Path           string `json:"path"`
	ContentHash    string `json:"contentHash"`
}

// FileWithProvenance prepends the deterministic provenance header; the
// content hash covers everything after the header block.
func FileWithProvenance(p Provenance, body string) (string, error) {
	digest := sha256.Sum256([]byte(body))
	p.ContentHash = hex.EncodeToString(digest[:])
	header, err := json.Marshal(p)
	if err != nil {
		return "", err
	}
	return "// Code generated by GoToTS for TSTS. DO NOT EDIT.\n" +
		"// @gotots-generated " + string(header) + "\n\n" + body, nil
}

// Package prints one translated package into a single TypeScript module:
// classes for named structs (methods attached), then functions, each in
// sorted name order. module carries the package identity, the
// language-ABI specifiers, and the co-generated import environment; the
// body is printed first so only referenced packages are imported.
func Package(module *Module, structs []*ir.Struct, functions []*ir.Func) (string, error) {
	sortedStructs := append([]*ir.Struct{}, structs...)
	sort.Slice(sortedStructs, func(i, j int) bool { return sortedStructs[i].Name < sortedStructs[j].Name })
	sorted := append([]*ir.Func{}, functions...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var body strings.Builder
	for _, structDecl := range sortedStructs {
		body.WriteString("\n")
		if err := printStruct(&body, module, structDecl); err != nil {
			return "", err
		}
	}
	for _, function := range sorted {
		body.WriteString("\n")
		if err := printFunc(&body, module, function); err != nil {
			return "", err
		}
	}
	return module.importLines() + body.String(), nil
}

// printStruct emits one named struct as a class whose constructor takes
// every field in declaration order (composite literals pass explicit
// zeros for omitted fields, so construction is always total).
func printStruct(out *strings.Builder, module *Module, structDecl *ir.Struct) error {
	p := &printer{out: out, module: module}
	export := ""
	if structDecl.Exported {
		export = "export "
	}
	p.line("%sclass %s {", export, structDecl.Name)
	p.indent++
	var params []string
	for _, field := range structDecl.Fields {
		spelled, err := p.tsType(field.Type)
		if err != nil {
			return fmt.Errorf("%s: %w", structDecl.ID, err)
		}
		p.line("%s: %s;", field.Name, spelled)
		params = append(params, field.Name+": "+spelled)
	}
	p.line("constructor(%s) {", strings.Join(params, ", "))
	p.indent++
	for _, field := range structDecl.Fields {
		p.line("this.%s = %s;", field.Name, field.Name)
	}
	p.indent--
	p.line("}")
	if err := printStructValueContract(p, structDecl); err != nil {
		return fmt.Errorf("%s: %w", structDecl.ID, err)
	}
	sortedMethods := append([]*ir.Func{}, structDecl.Methods...)
	sort.Slice(sortedMethods, func(i, j int) bool { return sortedMethods[i].Name < sortedMethods[j].Name })
	for _, method := range sortedMethods {
		if err := printMethod(p, method); err != nil {
			return err
		}
	}
	p.indent--
	p.line("}")
	return nil
}

// printStructValueContract emits the value-semantics members of every
// struct class: a deep clone along the value-struct spine, an in-place
// field overwrite (so aliases of the value observe whole-value stores,
// exactly like Go's memory write), and a fresh zero value. The names
// carry a "$" that no Go identifier can spell, so no source method can
// collide.
func printStructValueContract(p *printer, structDecl *ir.Struct) error {
	clone := make([]string, 0, len(structDecl.Fields))
	for _, field := range structDecl.Fields {
		if field.Type.Kind == ir.KindStruct {
			clone = append(clone, "this."+field.Name+".goClone$()")
		} else {
			clone = append(clone, "this."+field.Name)
		}
	}
	p.line("goClone$(): %s {", structDecl.Name)
	p.indent++
	p.line("return new %s(%s);", structDecl.Name, strings.Join(clone, ", "))
	p.indent--
	p.line("}")

	p.line("goSet$(other: %s): void {", structDecl.Name)
	p.indent++
	for _, field := range structDecl.Fields {
		if field.Type.Kind == ir.KindStruct {
			p.line("this.%s.goSet$(other.%s);", field.Name, field.Name)
		} else {
			p.line("this.%s = other.%s;", field.Name, field.Name)
		}
	}
	p.indent--
	p.line("}")

	zeros := make([]string, 0, len(structDecl.Fields))
	for _, field := range structDecl.Fields {
		zero, err := p.zeroLiteral(field.Type)
		if err != nil {
			return err
		}
		zeros = append(zeros, zero)
	}
	p.line("static goZero$(): %s {", structDecl.Name)
	p.indent++
	p.line("return new %s(%s);", structDecl.Name, strings.Join(zeros, ", "))
	p.indent--
	p.line("}")
	return nil
}

// printMethod emits one method. A pointer receiver binds the instance; a
// value receiver binds a clone on entry, so receiver mutations never
// reach the caller.
func printMethod(p *printer, method *ir.Func) error {
	p.temps = 0
	signature, err := p.functionSignature(method)
	if err != nil {
		return fmt.Errorf("%s: %w", method.ID, err)
	}
	p.line("%s%s {", method.Name, signature)
	p.indent++
	if method.Receiver.Type.Kind == ir.KindStruct {
		p.line("const %s = this.goClone$();", method.Receiver.Name)
	} else {
		p.line("const %s = this;", method.Receiver.Name)
	}
	if err := p.printBlockBody(method.Body); err != nil {
		return fmt.Errorf("%s: %w", method.ID, err)
	}
	p.indent--
	p.line("}")
	return nil
}

// printer carries per-function emission state and the module context.
type printer struct {
	out    *strings.Builder
	module *Module
	indent int
	temps  int
}

func (p *printer) line(format string, args ...any) {
	p.out.WriteString(strings.Repeat("  ", p.indent))
	fmt.Fprintf(p.out, format, args...)
	p.out.WriteString("\n")
}

func (p *printer) temp() string {
	name := fmt.Sprintf("_t%d", p.temps)
	p.temps++
	return name
}

func printFunc(out *strings.Builder, module *Module, function *ir.Func) error {
	p := &printer{out: out, module: module}
	signature, err := p.functionSignature(function)
	if err != nil {
		return fmt.Errorf("%s: %w", function.ID, err)
	}
	export := ""
	if function.Exported {
		export = "export "
	}
	p.line("%sfunction %s%s {", export, function.Name, signature)
	p.indent++
	if err := p.printBlockBody(function.Body); err != nil {
		return fmt.Errorf("%s: %w", function.ID, err)
	}
	p.indent--
	p.line("}")
	return nil
}

func (p *printer) functionSignature(function *ir.Func) (string, error) {
	var params []string
	for _, parameter := range function.Params {
		spelled, err := p.tsType(parameter.Type)
		if err != nil {
			return "", err
		}
		params = append(params, parameter.Name+": "+spelled)
	}
	result, err := p.tsResultType(function.Results)
	if err != nil {
		return "", err
	}
	return "(" + strings.Join(params, ", ") + "): " + result, nil
}

// tsType spells the static TypeScript type of one IR type, qualifying
// named types from other unit packages with their module alias.
func (p *printer) tsType(t ir.Type) (string, error) {
	switch t.Kind {
	case ir.KindBool:
		return "boolean", nil
	case ir.KindString:
		return "string", nil
	case ir.KindFloat32, ir.KindFloat64:
		return "number", nil
	case ir.KindInt8:
		return "goabi.GoInt8", nil
	case ir.KindInt16:
		return "goabi.GoInt16", nil
	case ir.KindInt32:
		return "goabi.GoInt32", nil
	case ir.KindInt64:
		return "goabi.GoInt64", nil
	case ir.KindInt:
		return "goabi.GoInt", nil
	case ir.KindUint8:
		return "goabi.GoUint8", nil
	case ir.KindUint16:
		return "goabi.GoUint16", nil
	case ir.KindUint32:
		return "goabi.GoUint32", nil
	case ir.KindUint64:
		return "goabi.GoUint64", nil
	case ir.KindUint:
		return "goabi.GoUint", nil
	case ir.KindUintptr:
		return "goabi.GoUintptr", nil
	case ir.KindPointer:
		name, err := p.module.symbol(t.Pkg, t.Named)
		if err != nil {
			return "", err
		}
		return name + " | undefined", nil
	case ir.KindStruct:
		return p.module.symbol(t.Pkg, t.Named)
	case ir.KindSlice:
		element, err := p.tsType(*t.Elem)
		if err != nil {
			return "", err
		}
		return "gosl.GoSliceValue<" + element + ">", nil
	case ir.KindMap:
		key, err := p.tsType(*t.Key)
		if err != nil {
			return "", err
		}
		value, err := p.tsType(*t.Elem)
		if err != nil {
			return "", err
		}
		return "gort.GoMap<" + key + ", " + value + ">", nil
	}
	return "", fmt.Errorf("no TypeScript spelling for IR type %q", t.Go)
}

func (p *printer) tsResultType(results []ir.Var) (string, error) {
	switch len(results) {
	case 0:
		return "void", nil
	case 1:
		return p.tsType(results[0].Type)
	default:
		var parts []string
		for _, result := range results {
			spelled, err := p.tsType(result.Type)
			if err != nil {
				return "", err
			}
			parts = append(parts, spelled)
		}
		return "readonly [" + strings.Join(parts, ", ") + "]", nil
	}
}
