package emit_test

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/tsoniclang/gotots/internal/emit"
	"github.com/tsoniclang/gotots/internal/load"
	"github.com/tsoniclang/gotots/internal/target/tsgo"
)

func TestNamedStructDefinitionScalesByFieldsWhileUseSitesStayConstant(t *testing.T) {
	fieldCounts := []int{8, 16, 32}
	printed := make([]string, len(fieldCounts))
	sizes := make([]int, len(fieldCounts))
	for index, fieldCount := range fieldCounts {
		emission := compileScalingStruct(t, fieldCount)
		source := structTargetSource(t, emission)
		assertStructOperationWidths(t, source, fieldCount)
		printed[index] = printAndTypecheckScalingStruct(t, emission)
		sizes[index] = len(printed[index])
	}

	firstDelta := sizes[1] - sizes[0]
	secondDelta := sizes[2] - sizes[1]
	if firstDelta <= 0 ||
		secondDelta*10 < firstDelta*17 ||
		secondDelta*10 > firstDelta*23 {
		t.Fatalf(
			"generated bytes = %v; doubling-field deltas %d/%d are not linear",
			sizes,
			firstDelta,
			secondDelta,
		)
	}
	var useSites string
	for index, target := range printed {
		start := strings.Index(target, "export function CopyRecord")
		if start < 0 {
			t.Fatal("scaling artifact lacks use-site functions")
		}
		current := target[start:]
		if index == 0 {
			useSites = current
			continue
		}
		if current != useSites {
			t.Fatal("copy/assignment/equality/method use sites grew with field count")
		}
	}
}

func compileScalingStruct(t *testing.T, fieldCount int) emit.ProgramEmission {
	t.Helper()
	directory := t.TempDir()
	writeProgramFile(
		t,
		filepath.Join(directory, "go.mod"),
		"module example.com/scaling\n\ngo 1.26.4\n",
	)
	var source strings.Builder
	source.WriteString("package scaling\n\ntype Record struct {\n")
	for index := range fieldCount {
		fmt.Fprintf(&source, "\tF%d int32\n", index)
	}
	source.WriteString(`}

func CopyRecord(value Record) Record {
	copy := value
	return copy
}

func AssignRecord(value Record) Record {
	var target Record
	target = value
	return target
}

func EqualRecord(left, right Record) bool {
	return left == right
}

func (value Record) WithFirst(next int32) Record {
	value.F0 = next
	return value
}

func InvokeRecord(value Record, next int32) Record {
	return value.WithFirst(next)
}
`)
	writeProgramFile(t, filepath.Join(directory, "source.go"), source.String())
	program, err := load.Load(context.Background(), load.Request{
		Directory: directory,
		Pattern:   ".",
	})
	if err != nil {
		t.Fatal(err)
	}
	roots, err := emit.ExportedAPIRoots(program.Roots()[0])
	if err != nil {
		t.Fatal(err)
	}
	emission, err := emit.Compile(program, roots)
	if err != nil {
		t.Fatal(err)
	}
	return emission
}

func assertStructOperationWidths(
	t *testing.T,
	source tsgo.SourceFile,
	fieldCount int,
) {
	t.Helper()
	class := targetClass(t, source, "Record")
	members := class.Members()
	constructor := members[1].(tsgo.ConstructorDeclaration)
	zero := members[2].(tsgo.MethodDeclaration)
	copyMethod := members[3].(tsgo.MethodDeclaration)
	assign := members[4].(tsgo.MethodDeclaration)
	equal := members[5].(tsgo.MethodDeclaration)
	if len(constructor.Parameters()) != fieldCount ||
		newArgumentCount(zero) != fieldCount ||
		newArgumentCount(copyMethod) != fieldCount ||
		len(assign.Body().(tsgo.Block).Statements()) != fieldCount ||
		equalityLeafCount(
			equal.Body().(tsgo.Block).Statements()[0].(tsgo.ReturnStatement).Expression(),
		) != fieldCount {
		t.Fatalf("Record operations do not each account for %d fields", fieldCount)
	}
}

func newArgumentCount(method tsgo.MethodDeclaration) int {
	result := method.Body().(tsgo.Block).Statements()[0].(tsgo.ReturnStatement).Expression().(tsgo.NewExpression)
	return len(result.Arguments())
}

func equalityLeafCount(expression tsgo.Expression) int {
	binary, ok := expression.(tsgo.BinaryExpression)
	if !ok {
		return 0
	}
	if binary.OperatorToken().Kind() == tsgo.SyntaxKindAmpersandAmpersandToken {
		return equalityLeafCount(binary.Left()) + equalityLeafCount(binary.Right())
	}
	if binary.OperatorToken().Kind() == tsgo.SyntaxKindEqualsEqualsEqualsToken {
		return 1
	}
	return 0
}

func printAndTypecheckScalingStruct(
	t *testing.T,
	emission emit.ProgramEmission,
) string {
	t.Helper()
	workingDirectory := t.TempDir()
	client, err := tsgo.StartClient(repositoryRoot(), workingDirectory)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := client.Close(); err != nil {
			t.Errorf("close TS-Go client: %v", err)
		}
	})
	var sourceText string
	var targetPaths []string
	for _, file := range emission.Files() {
		printed, err := client.PrintNode(file.SourceFile(), tsgo.PrintOptions{})
		if err != nil {
			t.Fatal(err)
		}
		targetPath := filepath.Join(
			workingDirectory,
			filepath.FromSlash(file.OutputPath()),
		)
		writeProgramFile(t, targetPath, printed)
		targetPaths = append(targetPaths, targetPath)
		if file.Kind() == emit.TargetFileSource {
			sourceText = printed
		}
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	arguments := []string{
		"--target", "es2022",
		"--module", "nodenext",
		"--moduleResolution", "nodenext",
		"--strict",
		"--noEmit",
	}
	arguments = append(arguments, targetPaths...)
	if err := tsgo.Compile(
		ctx,
		repositoryRoot(),
		workingDirectory,
		arguments,
	); err != nil {
		t.Fatal(err)
	}
	return sourceText
}
