#!/usr/bin/env python3
"""Transform-assisted hand port for fixture D1 (diagnostics keyToMessage).

Reads the exact manifest span from the pinned corpus and re-expresses the
Go switch as the equivalent source-shaped TypeScript switch. Deterministic:
output depends only on the manifest span bytes.

Usage: GOTOTS_CORPUS_DIR=<pinned tsgo checkout> python3 d1_transform.py
Run from the repository root; writes calibration/handports/D1.ts.
"""
import json, os, re, sys

corpus = os.environ.get("GOTOTS_CORPUS_DIR")
if not corpus:
    sys.exit("GOTOTS_CORPUS_DIR is required")
fixtures = json.load(open("calibration/calibration-manifest.json"))["fixtures"]
d1 = next(f for f in fixtures if f["fixtureId"] == "D1")
src = open(os.path.join(corpus, d1["sourceFile"]), "rb").read()
span = src[d1["startByte"]:d1["endByte"]].decode()

case_re = re.compile(r'^\tcase "([^"]+)":\n\t\treturn (\w+)$', re.M)
cases = case_re.findall(span)
# Fail closed: every Go case line must be consumed by the pattern.
want = span.count("\tcase ")
if len(cases) != want:
    sys.exit(f"transform matched {len(cases)} cases; span has {want}")

out = ["// Hand port D1 — diagnostics.keyToMessage, transform-assisted",
       "// (generated by tools/d1_transform.py from the exact manifest span;",
       "// same key/message pairs in the same order; *Message nil maps to",
       "// undefined).",
       "function keyToMessage(key: Key): Message | undefined {",
       "  switch (key) {"]
for key, name in cases:
    out.append(f'    case "{key}":')
    out.append(f"      return {name};")
out.append("    default:")
out.append("      return undefined;")
out.append("  }")
out.append("}")
open("calibration/handports/D1.ts", "w").write("\n".join(out) + "\n")
print(f"D1.ts: {len(cases)} cases")
