// Universe and attestation contract fixtures: symlinked source paths,
// tampered-but-clean trees, submodule gitlinks, generated-file markers,
// unselected packages, and build-profile selection variation.
package census

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/tsoniclang/gotots/internal/pinning"
	"github.com/tsoniclang/gotots/internal/profile"
)

// TestCensusThroughSymlinkedSourcePath proves a symlinked checkout path
// resolves to the same attested census (publication containment already
// resolves symlinks; the census itself must not care).
func TestCensusThroughSymlinkedSourcePath(t *testing.T) {
	dir, revision := writeFixtureRepo(t, basicFixtureFiles())
	prof := writeFixtureConfig(t, revision, basicFixtureProfile())

	linkParent, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(linkParent, "source-link")
	if err := os.Symlink(dir, link); err != nil {
		t.Fatal(err)
	}
	result, err := Run(prof, link, "fixture")
	if err != nil {
		t.Fatalf("census through symlink: %v", err)
	}
	if result.Report.Production.Bodies == 0 {
		t.Fatal("symlinked census produced no bodies")
	}
}

// TestCensusRejectsTamperedTrackedFile proves content attestation catches
// a modified tracked file even when git status has been silenced.
func TestCensusRejectsTamperedTrackedFile(t *testing.T) {
	dir, revision := writeFixtureRepo(t, basicFixtureFiles())
	prof := writeFixtureConfig(t, revision, basicFixtureProfile())

	target := filepath.Join(dir, "b.test", "b.go")
	if err := os.WriteFile(target, []byte("package btest\n\nconst Value = 8\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// Silence git's change tracking so cleanliness alone would pass.
	runGit(t, dir, "update-index", "--assume-unchanged", "b.test/b.go")
	if clean, err := pinning.CheckClean(dir); err != nil || !clean {
		t.Fatalf("fixture precondition: checkout should look clean (clean=%v err=%v)", clean, err)
	}

	_, err := Run(prof, dir, "fixture")
	if err == nil || !strings.Contains(err.Error(), "does not match the pinned commit blob") {
		t.Fatalf("expected blob-mismatch failure, got %v", err)
	}
}

// TestCensusRecordsSubmoduleGitlinks proves nested-repository gitlinks are
// pinned with their immutable revisions.
func TestCensusRecordsSubmoduleGitlinks(t *testing.T) {
	dir, _ := writeFixtureRepo(t, basicFixtureFiles())

	// Create the gitlink with plumbing: no clone or network involved.
	inner := t.TempDir()
	runGit(t, inner, "init", "-q")
	if err := os.WriteFile(filepath.Join(inner, "README"), []byte("nested\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runGit(t, inner, "add", "-A")
	runGit(t, inner, "commit", "-q", "-m", "nested")
	innerRevision := runGit(t, inner, "rev-parse", "HEAD")

	runGit(t, dir, "update-index", "--add", "--cacheinfo", "160000,"+innerRevision+",vendor/nested")
	runGit(t, dir, "commit", "-q", "-m", "add gitlink")
	if err := os.MkdirAll(filepath.Join(dir, "vendor", "nested"), 0o755); err != nil {
		t.Fatal(err)
	}
	revision := runGit(t, dir, "rev-parse", "HEAD")
	prof := writeFixtureConfig(t, revision, basicFixtureProfile())

	result, err := Run(prof, dir, "fixture")
	if err != nil {
		t.Fatalf("census: %v", err)
	}
	submodules := result.Inventory.Universe.Submodules
	if len(submodules) != 1 || submodules[0].Path != "vendor/nested" || submodules[0].Revision != innerRevision {
		t.Fatalf("gitlink not pinned: %+v", submodules)
	}
}

// TestGeneratedFileMarkerIsPositional proves the generated-code convention
// is applied positionally: a marker after the first non-comment text does
// not mark the file, and a conforming marker captures generator identity.
func TestGeneratedFileMarkerIsPositional(t *testing.T) {
	files := basicFixtureFiles()
	files["a/genuine_generated.go"] = "// Code generated by fixturegen. DO NOT EDIT.\n\npackage a\n\nconst Generated = 1\n"
	files["a/mentions_marker.go"] = "package a\n\n// Code generated by fixturegen. DO NOT EDIT.\nconst NotGenerated = 2\n"
	dir, revision := writeFixtureRepo(t, files)
	prof := writeFixtureConfig(t, revision, basicFixtureProfile())

	result, err := Run(prof, dir, "fixture")
	if err != nil {
		t.Fatalf("census: %v", err)
	}
	byPath := map[string]FileRecord{}
	for _, record := range result.Report.Files {
		byPath[record.Path] = record
	}
	genuine := byPath["a/genuine_generated.go"]
	if !genuine.Generated || genuine.GeneratedBy != "// Code generated by fixturegen. DO NOT EDIT." {
		t.Errorf("conforming marker not captured: %+v", genuine)
	}
	if byPath["a/mentions_marker.go"].Generated {
		t.Errorf("mid-file marker wrongly classified the file as generated")
	}
}

// TestUnclassifiedPackagePartitionAndEdge proves module packages
// matching no rule are counted as coverage defects and that selected
// imports of them are contradictions — total classification has no
// silent bucket.
func TestUnclassifiedPackagePartitionAndEdge(t *testing.T) {
	files := basicFixtureFiles()
	files["stray/stray.go"] = "package stray\n\nconst V = 1\n"
	files["a/uses_stray.go"] = "package a\n\nimport \"example.com/fix/stray\"\n\nfunc UsesStray() int { return stray.V }\n"
	dir, revision := writeFixtureRepo(t, files)
	prof := writeFixtureConfig(t, revision, basicFixtureProfile())

	result, err := Run(prof, dir, "fixture")
	if err != nil {
		t.Fatalf("census: %v", err)
	}
	if result.Report.Partition.Unclassified != 1 {
		t.Errorf("expected 1 unclassified package, got %d", result.Report.Partition.Unclassified)
	}
	found := false
	for _, edge := range result.Report.Contradictions {
		if edge.To == "example.com/fix/stray" && edge.Class == "unclassified" && edge.Scope == "production" {
			found = true
		}
	}
	if !found {
		t.Errorf("unselected-dependency contradiction missing: %+v", result.Report.Contradictions)
	}
	for _, blocker := range result.Report.Blockers {
		if strings.Contains(blocker, "stray") {
			return
		}
	}
	t.Errorf("unclassified contradiction not surfaced as blocker: %v", result.Report.Blockers)
}

// TestBuildProfileSelectsFiles proves build-profile identity changes file
// selection deterministically: a GOOS-constrained file is selected under
// its platform profile and ignored (but still attested) elsewhere.
func TestBuildProfileSelectsFiles(t *testing.T) {
	toolchain, err := measuredToolchain()
	if err != nil {
		t.Fatal(err)
	}
	otherOS := "windows"
	if toolchain.GOOS == "windows" {
		otherOS = "linux"
	}
	files := basicFixtureFiles()
	files["a/plat_"+otherOS+".go"] = "package a\n\nconst PlatformOnly = 1\n"
	dir, revision := writeFixtureRepo(t, files)
	prof := writeFixtureConfig(t, revision, basicFixtureProfile())

	result, err := Run(prof, dir, "fixture")
	if err != nil {
		t.Fatalf("census: %v", err)
	}
	for _, pkg := range result.Inventory.Module {
		if pkg.ImportPath != "example.com/fix/a" {
			continue
		}
		platFile := "a/plat_" + otherOS + ".go"
		for _, selected := range pkg.GoFiles {
			if selected == platFile {
				t.Fatalf("%s selected under %s profile", platFile, toolchain.GOOS)
			}
		}
		for _, ignored := range pkg.IgnoredGoFiles {
			if ignored == platFile {
				return
			}
		}
		t.Fatalf("%s missing from ignoredGoFiles: %+v", platFile, pkg.IgnoredGoFiles)
	}
	t.Fatal("package a missing from inventory")
}

// TestTestDiscoveryLedgerContract proves the ledger follows the toolchain
// discovery contract exactly: _test.go files only, signature evidence
// required, TestMain classified.
func TestTestDiscoveryLedgerContract(t *testing.T) {
	files := basicFixtureFiles()
	files["a/discovery_test.go"] = `package a

import "testing"

func TestMain(m *testing.M) {}
func TestReal(t *testing.T) {}
func BenchmarkReal(b *testing.B) {}
func Testwrong(value int) int { return value }
`
	// A discovery-shaped name in test-support production code is not a
	// test function.
	files["support/support_extra.go"] = "package support\n\nfunc TestLike() {}\n"
	dir, revision := writeFixtureRepo(t, files)
	prof := writeFixtureConfig(t, revision, basicFixtureProfile())

	result, err := Run(prof, dir, "fixture")
	if err != nil {
		t.Fatalf("census: %v", err)
	}
	kinds := map[string]string{}
	for _, record := range result.Report.TestFunctions {
		kinds[record.ID] = record.Kind
	}
	expectKind := func(idSuffix, kind string) {
		for id, k := range kinds {
			if strings.HasSuffix(id, idSuffix) {
				if k != kind {
					t.Errorf("%s classified %q, want %q", id, k, kind)
				}
				return
			}
		}
		t.Errorf("ledger entry with suffix %q missing: %v", idSuffix, kinds)
	}
	expectKind("::func::TestMain", "testmain")
	expectKind("::func::TestReal", "test")
	expectKind("::func::BenchmarkReal", "benchmark")
	for id := range kinds {
		if strings.Contains(id, "Testwrong") || strings.Contains(id, "TestLike") {
			t.Errorf("non-discovery function wrongly in ledger: %s", id)
		}
	}
}

// TestPublicationIgnoresForeignStaging proves an interrupted prior
// publication (a stale staging directory) neither blocks nor is disturbed
// by a new publication.
func TestPublicationIgnoresForeignStaging(t *testing.T) {
	source := makeSourceDir(t)
	parent := t.TempDir()
	stale := filepath.Join(parent, ".gotots-staging-stale")
	if err := os.MkdirAll(stale, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(stale, "partial.json"), []byte("{}"), 0o644); err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(parent, "bundle")
	if err := WriteReports(publishResult(t, source), out); err != nil {
		t.Fatalf("publish beside stale staging: %v", err)
	}
	if _, err := VerifyBundle(out); err != nil {
		t.Fatalf("bundle verify: %v", err)
	}
	if _, err := os.Stat(filepath.Join(stale, "partial.json")); err != nil {
		t.Errorf("foreign staging directory was disturbed: %v", err)
	}
}

// TestProfileFieldsHaveFixtureDispositions forces a reviewed fixture
// disposition for every field of the profile schema: adding a field
// without extending the fixture matrix fails this gate.
func TestProfileFieldsHaveFixtureDispositions(t *testing.T) {
	dispositions := map[string]string{
		"schemaVersion":  "fixtureutil_test.go writeFixtureConfig",
		"product":        "fixtureutil_test.go writeFixtureConfig",
		"goModule":       "fixtureutil_test.go writeFixtureConfig",
		"pin":            "fixtureutil_test.go writeFixtureConfig + attestation fixtures",
		"buildProfiles":  "TestBuildProfileSelectsFiles",
		"sourceUniverse": "basicFixtureProfile rules exercise selected/test-only/outside/tooling dispositions; TestUnclassifiedPackagePartitionAndEdge covers total-classification defects; internal/profile rules_test.go covers override/ambiguity/containment",
		"productSurface": "basicFixtureProfile carries the mandatory public-api-set root; internal/profile product_test.go covers kind/binding/selector/duplicate validation",
		"notes":          "documentation-only field, no behavior",
	}
	for _, field := range profileJSONFields(t) {
		if _, reviewed := dispositions[field]; !reviewed {
			t.Errorf("profile field %q has no reviewed fixture disposition; extend the fixture matrix", field)
		}
	}
}

func profileJSONFields(t *testing.T) []string {
	t.Helper()
	var fields []string
	profileType := reflect.TypeOf(profile.Profile{})
	for i := range profileType.NumField() {
		name, _, _ := strings.Cut(profileType.Field(i).Tag.Get("json"), ",")
		if name != "" && name != "-" {
			fields = append(fields, name)
		}
	}
	return fields
}
